model_params:
  name: 'BetaTCVAE'
  in_channels: 3
  latent_dim: 10
  anneal_steps: 10000
  alpha: 1.
  beta:  6.
  gamma: 1.

exp_params:
  dataset: celeba
  data_path: "C:\\Users\\Raymond\\Documents\\Programming\\Research project\\PyTorch-VAE\\dataset"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "F:logs/"
  name: "BetaTCVAE"
  manual_seed: 1265
