model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 128

exp_params:
  dataset: celldata
  #data_path: "C:\\Users\\raymo\\Documents\\Programming\\researchproject\\PyTorch-VAE\\dataset\\celldata\\"
  data_path: "C:\\Users\\Raymond\\Documents\\Programming\\Research project\\PyTorch-VAE\\dataset\\celldata\\"
  batch_size: 144 # Better to have a square number
  LR: 0.00001
  weight_decay: 0.0
  #scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 200

logging_params:
  #save_dir: "C:/logs/"
  save_dir: "F:logs/"
  name: "VanillaVAE"
  manual_seed: 9344

custom_params:
  input_size: 2239 #MAX: 2239
