model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 128

exp_params:
  dataset: celldata
  data_path: "C:\\Users\\raymo\\Documents\\Programming\\researchproject\\PyTorch-VAE\\dataset\\celldata\\"
  img_size: 64
  batch_size: 4 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 1

logging_params:
  save_dir: "C:/logs/"
  name: "VanillaVAE"
  manual_seed: 1265
